### PR TITLE
added return type and changed required php version to minimum 8.0

### PR DESCRIPTION
**Pull request by mgbmrjnppv**

### CODE REVIEW

**Comment by dbu** [comment]
thanks. please adjust the build matrix and remove all 7.x builds. you could add 8.2 while touching it.

**Comment by mgbmrjnppv** [comment]
> thanks. please adjust the build matrix and remove all 7.x builds. you could add 8.2 while touching it.

glad to help. I don't understand what you mean by that whole sentance with the build matrix. could you explain it a bit better?

**Comment by dbu** [comment]
the build matrix for github actions is configured here: https://github.com/liip/serializer/blob/2.x/.github/workflows/ci.yml

it tells github to build this project with php 7.1 to 8.1. now that you restrict the compatibility to php 8, you need to remove the old php versions from that list. the CI builds that you can see above fails because composer tells that the library is not compatible with PHP 7.3.

**Comment by dbu** [comment]
released as https://github.com/liip/serializer/releases/tag/2.3.0

**Pull request merged**
